import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { generatePassword } from "../calculations.js";

export function registerPassword(server: McpServer) {
  server.registerTool(
    "generate_password",
    {
      title: "Password Generator",
      description:
        "Generate a cryptographically secure random password with configurable length and character types. Returns password, strength rating, and entropy.",
      inputSchema: z.object({
        length: z
          .number()
          .int()
          .min(4)
          .max(128)
          .default(16)
          .describe("Password length (default: 16)"),
        uppercase: z
          .boolean()
          .default(true)
          .describe("Include uppercase letters (default: true)"),
        lowercase: z
          .boolean()
          .default(true)
          .describe("Include lowercase letters (default: true)"),
        numbers: z
          .boolean()
          .default(true)
          .describe("Include numbers (default: true)"),
        symbols: z
          .boolean()
          .default(true)
          .describe("Include symbols (default: true)"),
      }),
    },
    async ({ length, uppercase, lowercase, numbers, symbols }) => {
      const result = generatePassword(length, {
        uppercase,
        lowercase,
        numbers,
        symbols,
      });

      const text = [
        `Password: ${result.password}`,
        `Strength: ${result.strength}`,
        `Entropy: ${result.entropy_bits} bits`,
        ``,
        `Generated by KeyForge | More tools: https://keyforge.thicket.sh?utm_source=mcp&utm_medium=tool`,
      ].join("\n");

      return { content: [{ type: "text", text }] };
    }
  );
}
